version: '2'
services:
  my-golang-app-run:
    container_name: my-golang-app-run
    build: .
    command: go run main.go
    volumes:
      - ./src:/go/src/
    working_dir: /go/src
    ports:
      - "3030:3001"
    environment:
      PORT: 3001
  mysql:
    container_name: mysql-container
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=goland"
    ports:
      - "33061:3306"
