version: '2.1'
services:
  mysql:
    container_name: mysql-container
    image: mysql:5.7
    tty: true
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=goland"
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=secret --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 40s
      retries: 30
  my-golang-app-run:
    container_name: my-golang-app-run
    build: .
    command: go run main.go
    volumes:
      - ./src:/tmp/src/
    working_dir: /tmp/src
    ports:
      - "3030:3001"
    environment:
      PORT: 3001
    links:
      - mysql
    tty: true
    depends_on:
      mysql:
        condition: service_healthy
